export const LOGIN_USER = "LOGIN_USER"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"

export const LOGOUT_USER = "LOGOUT_USER"
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS"
export const API_ERROR = "LOGIN_API_ERROR"

export const SOCIAL_LOGIN = "SOCIAL_LOGIN"

export const RESET_LOGIN_FLAG = "RESET_LOGIN_FLAG"





// FOR E-SERIES
export const ACCOUNT_RESPONSE_SUCCESS = "ACCOUNT_RESPONSE_SUCCESS";
export const ACCOUNT_RESPONSE_ERROR = "ACCOUNT_RESPONSE_ERROR";
export const ACCOUNT_LOGIN = "ACCOUNT_LOGIN";
export const ACCOUNT_SIGN_UP = "ACCOUNT_SIGN_UP";
export const ACCOUNT_LOGOUT = "ACCOUNT_LOGOUT";
